
# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: PowerShell@2
  displayName: "Change productname"
  # To avoid name clashes with existing jars from other repos we refine the productname from http-connector-for-apache-kafka to aiven-http-connector-for-apache-kafka  
  # aiven is the original repo owning company we forked from
  inputs:
    targetType: 'inline'
    script: |
      "rootProject.name = 'aiven-http-connector-for-apache-kafka'" | Out-File "$(Build.SourcesDirectory)/settings.gradle"
- task: Gradle@2
  displayName: "Build kafka http connector"
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- task: PowerShell@2
  displayName: "Add productionversion as build tag"
  inputs:
    targetType: 'inline'
    script: |
      # Extract version from gradle.properties
      $text = Get-Content "$(Build.SourcesDirectory)/gradle.properties" | Out-String
      $text -match '=([0-9.]+)-'
      $rversion=$Matches.1
      Write-Host "Found version $rversion"
      Write-Host "##vso[build.addbuildtag]ProductVersion_$rversion"
- task: PublishBuildArtifacts@1
  displayName: "Publish jars to azure devops artifacts"
  enabled: true
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/build/distributions'
    ArtifactName: 'drop'
    publishLocation: 'Container'